apiVersion: v1
kind: Secret
metadata:
  name: aboveme-config
type: Opaque
stringData:
  config.cfg: |
    [default]
    QUERY_URL_PART1: {{ .Values.config.queryUrlPart1 }}
    QUERY_URL_PART2: {{ .Values.config.queryUrlPart2 }}
    BOUNDS: {{ .Values.config.bounds }}
    EXTRA_DATA_URL: {{ .Values.config.extraDataUrl }}
    USER_AGENT: {{ .Values.config.userAgent }}
    BROKER_ADDRESS: {{ .Values.config.brokerAddress }}
    BROKER_PORT: {{ .Values.config.brokerPort }}
    BROKER_USERNAME: {{ .Values.config.brokerUsername }}
    BROKER_PASSWORD: {{ .Values.config.brokerPassword }}
    MQTT_TOPIC: {{ .Values.config.mqttTopic }}
    SLEEP: {{ .Values.config.sleep }}